# Generated by Django 4.0.1 on 2022-01-22 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_imagefacetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageScriptKeysTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('script_key', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imagefacetable',
            name='script_key',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='imageloadertable',
            name='script_key',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
